# fly.toml app configuration file generated for my-chat-app-example on 2025-01-29T17:31:09+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'my-chat-app-example'
primary_region = 'fra'

[build]
  dockerfile = 'Dockerfile'

[http_service]
  internal_port = 5170
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
