version: 2.1

jobs:
  test:
    docker:
      - image: cimg/node:20.18.2
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            npm ci  # Installs dependencies from package-lock.json
      - run:
          name: Run tests
          command: |
            npm test  # Or your test command

  deploy:
    docker:
      - image: cimg/node:20.18.2
    steps:
      - checkout
      - run:
          name: Install Flyctl
          command: |
            curl -fsSL https://fly.io/install.sh | sh  # Install flyctl
      - run:
          name: Build the app
          command: |
            npm run build  # Build your project if necessary
      - run:
          name: Deploy to Fly.io
          command: |
            flyctl deploy --remote-only --config fly.toml  # Deploy the app using Fly.io
        environment:
          FLY_API_TOKEN: $FLY_API_TOKEN

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
